export const categories = [
  {
    name: "Smartphones",
    navigate: "smartphones",
  },
  {
    name: "Cars",
    navigate: "cars",
  },
  {
    name: "Bikes",
    navigate: "bikes",
  },
];

const applePhoneList = [
  { label: "iPhone", value: "iPhone" },
  { label: "iPhone 3G", value: "iPhone 3G" },
  { label: "iPhone 3GS", value: "iPhone 3GS" },
  { label: "iPhone 4", value: "iPhone 4" },
  { label: "iPhone 4S", value: "iPhone 4S" },
  { label: "iPhone 5", value: "iPhone 5" },
  { label: "iPhone 5C", value: "iPhone 5C" },
  { label: "iPhone 5S", value: "iPhone 5S" },
  { label: "iPhone 6", value: "iPhone 6" },
  { label: "iPhone 6 Plus", value: "iPhone 6 Plus" },
  { label: "iPhone 6S", value: "iPhone 6S" },
  { label: "iPhone 6S Plus", value: "iPhone 6S Plus" },
  { label: "iPhone SE (1st Gen)", value: "iPhone SE (1st Gen)" },
  { label: "iPhone 7", value: "iPhone 7" },
  { label: "iPhone 7 Plus", value: "iPhone 7 Plus" },
  { label: "iPhone 8", value: "iPhone 8" },
  { label: "iPhone 8 Plus", value: "iPhone 8 Plus" },
  { label: "iPhone X", value: "iPhone X" },
  { label: "iPhone XR", value: "iPhone XR" },
  { label: "iPhone XS", value: "iPhone XS" },
  { label: "iPhone XS Max", value: "iPhone XS Max" },
  { label: "iPhone 11", value: "iPhone 11" },
  { label: "iPhone 11 Pro", value: "iPhone 11 Pro" },
  { label: "iPhone 11 Pro Max", value: "iPhone 11 Pro Max" },
  { label: "iPhone SE (2nd Gen)", value: "iPhone SE (2nd Gen)" },
  { label: "iPhone 12", value: "iPhone 12" },
  { label: "iPhone 12 Mini", value: "iPhone 12 Mini" },
  { label: "iPhone 12 Pro", value: "iPhone 12 Pro" },
  { label: "iPhone 12 Pro Max", value: "iPhone 12 Pro Max" },
  { label: "iPhone 13", value: "iPhone 13" },
  { label: "iPhone 13 Mini", value: "iPhone 13 Mini" },
  { label: "iPhone 13 Pro", value: "iPhone 13 Pro" },
  { label: "iPhone 13 Pro Max", value: "iPhone 13 Pro Max" },
  { label: "iPhone SE (3rd Gen)", value: "iPhone SE (3rd Gen)" },
  { label: "iPhone 14", value: "iPhone 14" },
  { label: "iPhone 14 Plus", value: "iPhone 14 Plus" },
  { label: "iPhone 14 Pro", value: "iPhone 14 Pro" },
  { label: "iPhone 14 Pro Max", value: "iPhone 14 Pro Max" },
  { label: "iPhone 15", value: "iPhone 15" },
  { label: "iPhone 15 Plus", value: "iPhone 15 Plus" },
  { label: "iPhone 15 Pro", value: "iPhone 15 Pro" },
  { label: "iPhone 15 Pro Max", value: "iPhone 15 Pro Max" },
  { label: "iPhone 16 Plus", value: "iPhone 16 Plus" },
  { label: "iPhone 16 Pro", value: "iPhone 16 Pro" },
  { label: "iPhone 16 Pro Max", value: "iPhone 16 Pro Max" },
];

const samsungPhoneList = [
  { label: "Samsung Galaxy S", value: "Samsung Galaxy S" },
  { label: "Samsung Galaxy S II", value: "Samsung Galaxy S II" },
  { label: "Samsung Galaxy S III", value: "Samsung Galaxy S III" },
  { label: "Samsung Galaxy S4", value: "Samsung Galaxy S4" },
  { label: "Samsung Galaxy S5", value: "Samsung Galaxy S5" },
  { label: "Samsung Galaxy S6", value: "Samsung Galaxy S6" },
  { label: "Samsung Galaxy S6 Edge", value: "Samsung Galaxy S6 Edge" },
  { label: "Samsung Galaxy S6 Edge+", value: "Samsung Galaxy S6 Edge+" },
  { label: "Samsung Galaxy S7", value: "Samsung Galaxy S7" },
  { label: "Samsung Galaxy S7 Edge", value: "Samsung Galaxy S7 Edge" },
  { label: "Samsung Galaxy S8", value: "Samsung Galaxy S8" },
  { label: "Samsung Galaxy S8+", value: "Samsung Galaxy S8+" },
  { label: "Samsung Galaxy S9", value: "Samsung Galaxy S9" },
  { label: "Samsung Galaxy S9+", value: "Samsung Galaxy S9+" },
  { label: "Samsung Galaxy S10", value: "Samsung Galaxy S10" },
  { label: "Samsung Galaxy S10e", value: "Samsung Galaxy S10e" },
  { label: "Samsung Galaxy S10+", value: "Samsung Galaxy S10+" },
  { label: "Samsung Galaxy S10 5G", value: "Samsung Galaxy S10 5G" },
  { label: "Samsung Galaxy S20", value: "Samsung Galaxy S20" },
  { label: "Samsung Galaxy S20+", value: "Samsung Galaxy S20+" },
  { label: "Samsung Galaxy S20 Ultra", value: "Samsung Galaxy S20 Ultra" },
  { label: "Samsung Galaxy S20 FE", value: "Samsung Galaxy S20 FE" },
  { label: "Samsung Galaxy S21", value: "Samsung Galaxy S21" },
  { label: "Samsung Galaxy S21+", value: "Samsung Galaxy S21+" },
  { label: "Samsung Galaxy S21 Ultra", value: "Samsung Galaxy S21 Ultra" },
  { label: "Samsung Galaxy S21 FE", value: "Samsung Galaxy S21 FE" },
  { label: "Samsung Galaxy S22", value: "Samsung Galaxy S22" },
  { label: "Samsung Galaxy S22+", value: "Samsung Galaxy S22+" },
  { label: "Samsung Galaxy S22 Ultra", value: "Samsung Galaxy S22 Ultra" },
  { label: "Samsung Galaxy S23", value: "Samsung Galaxy S23" },
  { label: "Samsung Galaxy S23+", value: "Samsung Galaxy S23+" },
  { label: "Samsung Galaxy S23 Ultra", value: "Samsung Galaxy S23 Ultra" },
  { label: "Samsung Galaxy S23 FE", value: "Samsung Galaxy S23 FE" },
  { label: "Samsung Galaxy S24", value: "Samsung Galaxy S24" },
  { label: "Samsung Galaxy S24+", value: "Samsung Galaxy S24+" },
  { label: "Samsung Galaxy S24 Ultra", value: "Samsung Galaxy S24 Ultra" },
];

const huaweiPhoneList = [
  { label: "Huawei Ascend P1", value: "Huawei Ascend P1" },
  { label: "Huawei Ascend P2", value: "Huawei Ascend P2" },
  { label: "Huawei Ascend P6", value: "Huawei Ascend P6" },
  { label: "Huawei Ascend P7", value: "Huawei Ascend P7" },
  { label: "Huawei P8", value: "Huawei P8" },
  { label: "Huawei P9", value: "Huawei P9" },
  { label: "Huawei P10", value: "Huawei P10" },
  { label: "Huawei P20", value: "Huawei P20" },
  { label: "Huawei P20 Pro", value: "Huawei P20 Pro" },
  { label: "Huawei P30", value: "Huawei P30" },
  { label: "Huawei P30 Pro", value: "Huawei P30 Pro" },
  { label: "Huawei P40", value: "Huawei P40" },
  { label: "Huawei P40 Pro", value: "Huawei P40 Pro" },
  { label: "Huawei P40 Pro+", value: "Huawei P40 Pro+" },
  { label: "Huawei P50", value: "Huawei P50" },
  { label: "Huawei P50 Pro", value: "Huawei P50 Pro" },
  { label: "Huawei P50 Pocket", value: "Huawei P50 Pocket" },
  { label: "Huawei P60", value: "Huawei P60" },
  { label: "Huawei P60 Pro", value: "Huawei P60 Pro" },
  { label: "Huawei P60 Art", value: "Huawei P60 Art" },
  { label: "Huawei Mate 7", value: "Huawei Mate 7" },
  { label: "Huawei Mate 8", value: "Huawei Mate 8" },
  { label: "Huawei Mate 9", value: "Huawei Mate 9" },
  { label: "Huawei Mate 10", value: "Huawei Mate 10" },
  { label: "Huawei Mate 10 Pro", value: "Huawei Mate 10 Pro" },
  { label: "Huawei Mate 20", value: "Huawei Mate 20" },
  { label: "Huawei Mate 20 Pro", value: "Huawei Mate 20 Pro" },
  { label: "Huawei Mate 20 X", value: "Huawei Mate 20 X" },
  { label: "Huawei Mate 30", value: "Huawei Mate 30" },
  { label: "Huawei Mate 30 Pro", value: "Huawei Mate 30 Pro" },
  { label: "Huawei Mate 40", value: "Huawei Mate 40" },
  { label: "Huawei Mate 40 Pro", value: "Huawei Mate 40 Pro" },
  { label: "Huawei Mate 50", value: "Huawei Mate 50" },
  { label: "Huawei Mate 50 Pro", value: "Huawei Mate 50 Pro" },
  { label: "Huawei Mate X", value: "Huawei Mate X" },
  { label: "Huawei Mate Xs", value: "Huawei Mate Xs" },
  { label: "Huawei Mate X2", value: "Huawei Mate X2" },
  { label: "Huawei Mate X3", value: "Huawei Mate X3" },
  { label: "Huawei nova 2", value: "Huawei nova 2" },
  { label: "Huawei nova 3", value: "Huawei nova 3" },
  { label: "Huawei nova 4", value: "Huawei nova 4" },
  { label: "Huawei nova 5", value: "Huawei nova 5" },
  { label: "Huawei nova 6", value: "Huawei nova 6" },
  { label: "Huawei nova 7", value: "Huawei nova 7" },
  { label: "Huawei nova 8", value: "Huawei nova 8" },
  { label: "Huawei nova 9", value: "Huawei nova 9" },
  { label: "Huawei nova 10", value: "Huawei nova 10" },
  { label: "Huawei nova 11", value: "Huawei nova 11" },
];

const nokiaPhoneList = [
  { label: "Nokia N95", value: "Nokia N95" },
  { label: "Nokia 5800 XpressMusic", value: "Nokia 5800 XpressMusic" },
  { label: "Nokia N8", value: "Nokia N8" },
  { label: "Nokia Lumia 800", value: "Nokia Lumia 800" },
  { label: "Nokia Lumia 900", value: "Nokia Lumia 900" },
  { label: "Nokia Lumia 920", value: "Nokia Lumia 920" },
  { label: "Nokia Lumia 1020", value: "Nokia Lumia 1020" },
  { label: "Nokia Lumia 1320", value: "Nokia Lumia 1320" },
  { label: "Nokia Lumia 1520", value: "Nokia Lumia 1520" },
  { label: "Nokia Lumia 520", value: "Nokia Lumia 520" },
  { label: "Nokia Lumia 525", value: "Nokia Lumia 525" },
  { label: "Nokia Lumia 535", value: "Nokia Lumia 535" },
  { label: "Nokia Lumia 635", value: "Nokia Lumia 635" },
  { label: "Nokia Lumia 730", value: "Nokia Lumia 730" },
  { label: "Nokia Lumia 830", value: "Nokia Lumia 830" },
  { label: "Nokia Lumia 930", value: "Nokia Lumia 930" },
  { label: "Nokia 3", value: "Nokia 3" },
  { label: "Nokia 5", value: "Nokia 5" },
  { label: "Nokia 6", value: "Nokia 6" },
  { label: "Nokia 6.1", value: "Nokia 6.1" },
  { label: "Nokia 7", value: "Nokia 7" },
  { label: "Nokia 7 Plus", value: "Nokia 7 Plus" },
  { label: "Nokia 8", value: "Nokia 8" },
  { label: "Nokia 8 Sirocco", value: "Nokia 8 Sirocco" },
  { label: "Nokia 9 PureView", value: "Nokia 9 PureView" },
  { label: "Nokia 1", value: "Nokia 1" },
  { label: "Nokia 2", value: "Nokia 2" },
  { label: "Nokia 2.1", value: "Nokia 2.1" },
  { label: "Nokia 2.2", value: "Nokia 2.2" },
  { label: "Nokia 3.1", value: "Nokia 3.1" },
  { label: "Nokia 3.2", value: "Nokia 3.2" },
  { label: "Nokia 4.2", value: "Nokia 4.2" },
  { label: "Nokia 5.1", value: "Nokia 5.1" },
  { label: "Nokia 5.3", value: "Nokia 5.3" },
  { label: "Nokia 6.2", value: "Nokia 6.2" },
  { label: "Nokia 7.2", value: "Nokia 7.2" },
  { label: "Nokia 8.1", value: "Nokia 8.1" },
  { label: "Nokia X10", value: "Nokia X10" },
  { label: "Nokia X20", value: "Nokia X20" },
  { label: "Nokia G10", value: "Nokia G10" },
  { label: "Nokia G20", value: "Nokia G20" },
  { label: "Nokia G21", value: "Nokia G21" },
  { label: "Nokia XR20", value: "Nokia XR20" },
  { label: "Nokia C1", value: "Nokia C1" },
  { label: "Nokia C2", value: "Nokia C2" },
  { label: "Nokia C20", value: "Nokia C20" },
  { label: "Nokia C21", value: "Nokia C21" },
  { label: "Nokia C30", value: "Nokia C30" },
];

const sonyPhoneList = [
  { label: "Sony Xperia X10", value: "Sony Xperia X10" },
  { label: "Sony Xperia X8", value: "Sony Xperia X8" },
  { label: "Sony Xperia Arc", value: "Sony Xperia Arc" },
  { label: "Sony Xperia Arc S", value: "Sony Xperia Arc S" },
  { label: "Sony Xperia Play", value: "Sony Xperia Play" },
  { label: "Sony Xperia Neo", value: "Sony Xperia Neo" },
  { label: "Sony Xperia S", value: "Sony Xperia S" },
  { label: "Sony Xperia P", value: "Sony Xperia P" },
  { label: "Sony Xperia U", value: "Sony Xperia U" },
  { label: "Sony Xperia T", value: "Sony Xperia T" },
  { label: "Sony Xperia V", value: "Sony Xperia V" },
  { label: "Sony Xperia Z", value: "Sony Xperia Z" },
  { label: "Sony Xperia Z1", value: "Sony Xperia Z1" },
  { label: "Sony Xperia Z1 Compact", value: "Sony Xperia Z1 Compact" },
  { label: "Sony Xperia Z2", value: "Sony Xperia Z2" },
  { label: "Sony Xperia Z3", value: "Sony Xperia Z3" },
  { label: "Sony Xperia Z3 Compact", value: "Sony Xperia Z3 Compact" },
  { label: "Sony Xperia Z3+", value: "Sony Xperia Z3+" },
  { label: "Sony Xperia Z5", value: "Sony Xperia Z5" },
  { label: "Sony Xperia Z5 Compact", value: "Sony Xperia Z5 Compact" },
  { label: "Sony Xperia Z5 Premium", value: "Sony Xperia Z5 Premium" },
  { label: "Sony Xperia X", value: "Sony Xperia X" },
  { label: "Sony Xperia X Performance", value: "Sony Xperia X Performance" },
  { label: "Sony Xperia XA", value: "Sony Xperia XA" },
  { label: "Sony Xperia XA Ultra", value: "Sony Xperia XA Ultra" },
  { label: "Sony Xperia XZ", value: "Sony Xperia XZ" },
  { label: "Sony Xperia XZs", value: "Sony Xperia XZs" },
  { label: "Sony Xperia XZ1", value: "Sony Xperia XZ1" },
  { label: "Sony Xperia XZ1 Compact", value: "Sony Xperia XZ1 Compact" },
  { label: "Sony Xperia XZ2", value: "Sony Xperia XZ2" },
  { label: "Sony Xperia XZ2 Compact", value: "Sony Xperia XZ2 Compact" },
  { label: "Sony Xperia XZ3", value: "Sony Xperia XZ3" },
  { label: "Sony Xperia 1", value: "Sony Xperia 1" },
  { label: "Sony Xperia 1 II", value: "Sony Xperia 1 II" },
  { label: "Sony Xperia 1 III", value: "Sony Xperia 1 III" },
  { label: "Sony Xperia 1 IV", value: "Sony Xperia 1 IV" },
  { label: "Sony Xperia 1 V", value: "Sony Xperia 1 V" },
  { label: "Sony Xperia 5", value: "Sony Xperia 5" },
  { label: "Sony Xperia 5 II", value: "Sony Xperia 5 II" },
  { label: "Sony Xperia 5 III", value: "Sony Xperia 5 III" },
  { label: "Sony Xperia 5 IV", value: "Sony Xperia 5 IV" },
  { label: "Sony Xperia 5 V", value: "Sony Xperia 5 V" },
  { label: "Sony Xperia 10", value: "Sony Xperia 10" },
  { label: "Sony Xperia 10 II", value: "Sony Xperia 10 II" },
  { label: "Sony Xperia 10 III", value: "Sony Xperia 10 III" },
  { label: "Sony Xperia 10 IV", value: "Sony Xperia 10 IV" },
  { label: "Sony Xperia 10 V", value: "Sony Xperia 10 V" },
  { label: "Sony Xperia Pro", value: "Sony Xperia Pro" },
  { label: "Sony Xperia Pro-I", value: "Sony Xperia Pro-I" },
];

const lgPhoneList = [
  { label: "LG Optimus One", value: "LG Optimus One" },
  { label: "LG Optimus 2X", value: "LG Optimus 2X" },
  { label: "LG Optimus 3D", value: "LG Optimus 3D" },
  { label: "LG Optimus Black", value: "LG Optimus Black" },
  { label: "LG Optimus G", value: "LG Optimus G" },
  { label: "LG Optimus G Pro", value: "LG Optimus G Pro" },
  { label: "LG G2", value: "LG G2" },
  { label: "LG G3", value: "LG G3" },
  { label: "LG G4", value: "LG G4" },
  { label: "LG G5", value: "LG G5" },
  { label: "LG G6", value: "LG G6" },
  { label: "LG G7 ThinQ", value: "LG G7 ThinQ" },
  { label: "LG G8 ThinQ", value: "LG G8 ThinQ" },
  { label: "LG G8X ThinQ", value: "LG G8X ThinQ" },
  { label: "LG V10", value: "LG V10" },
  { label: "LG V20", value: "LG V20" },
  { label: "LG V30", value: "LG V30" },
  { label: "LG V35 ThinQ", value: "LG V35 ThinQ" },
  { label: "LG V40 ThinQ", value: "LG V40 ThinQ" },
  { label: "LG V50 ThinQ", value: "LG V50 ThinQ" },
  { label: "LG V50S ThinQ", value: "LG V50S ThinQ" },
  { label: "LG V60 ThinQ", value: "LG V60 ThinQ" },
  { label: "LG Velvet", value: "LG Velvet" },
  { label: "LG Velvet 2 Pro", value: "LG Velvet 2 Pro" },
  { label: "LG Wing", value: "LG Wing" },
  { label: "LG Q6", value: "LG Q6" },
  { label: "LG Q7", value: "LG Q7" },
  { label: "LG Q8", value: "LG Q8" },
  { label: "LG Q9", value: "LG Q9" },
  { label: "LG K10", value: "LG K10" },
  { label: "LG K20", value: "LG K20" },
  { label: "LG K30", value: "LG K30" },
  { label: "LG K40", value: "LG K40" },
  { label: "LG K50", value: "LG K50" },
  { label: "LG K61", value: "LG K61" },
  { label: "LG K92", value: "LG K92" },
  { label: "LG Stylo 3", value: "LG Stylo 3" },
  { label: "LG Stylo 4", value: "LG Stylo 4" },
  { label: "LG Stylo 5", value: "LG Stylo 5" },
  { label: "LG Stylo 6", value: "LG Stylo 6" },
];

const htcPhoneList = [
  { label: "HTC Dream (T-Mobile G1)", value: "HTC Dream (T-Mobile G1)" },
  { label: "HTC Magic", value: "HTC Magic" },
  { label: "HTC Hero", value: "HTC Hero" },
  { label: "HTC Tattoo", value: "HTC Tattoo" },
  { label: "HTC Legend", value: "HTC Legend" },
  { label: "HTC Desire", value: "HTC Desire" },
  { label: "HTC Desire HD", value: "HTC Desire HD" },
  { label: "HTC Desire Z", value: "HTC Desire Z" },
  { label: "HTC Wildfire", value: "HTC Wildfire" },
  { label: "HTC Wildfire S", value: "HTC Wildfire S" },
  { label: "HTC Sensation", value: "HTC Sensation" },
  { label: "HTC Sensation XE", value: "HTC Sensation XE" },
  { label: "HTC Sensation XL", value: "HTC Sensation XL" },
  { label: "HTC Evo 3D", value: "HTC Evo 3D" },
  { label: "HTC One X", value: "HTC One X" },
  { label: "HTC One X+", value: "HTC One X+" },
  { label: "HTC One S", value: "HTC One S" },
  { label: "HTC One V", value: "HTC One V" },
  { label: "HTC One M7", value: "HTC One M7" },
  { label: "HTC One M8", value: "HTC One M8" },
  { label: "HTC One M9", value: "HTC One M9" },
  { label: "HTC One A9", value: "HTC One A9" },
  { label: "HTC One X9", value: "HTC One X9" },
  { label: "HTC 10", value: "HTC 10" },
  { label: "HTC U Ultra", value: "HTC U Ultra" },
  { label: "HTC U Play", value: "HTC U Play" },
  { label: "HTC U11", value: "HTC U11" },
  { label: "HTC U11 Life", value: "HTC U11 Life" },
  { label: "HTC U11 Plus", value: "HTC U11 Plus" },
  { label: "HTC U12+", value: "HTC U12+" },
  { label: "HTC Desire 10 Pro", value: "HTC Desire 10 Pro" },
  { label: "HTC Desire 10 Lifestyle", value: "HTC Desire 10 Lifestyle" },
  { label: "HTC Desire 12", value: "HTC Desire 12" },
  { label: "HTC Desire 12+", value: "HTC Desire 12+" },
  { label: "HTC Desire 19+", value: "HTC Desire 19+" },
  { label: "HTC Exodus 1", value: "HTC Exodus 1" },
  { label: "HTC Exodus 1s", value: "HTC Exodus 1s" },
  { label: "HTC U19e", value: "HTC U19e" },
  { label: "HTC Wildfire E", value: "HTC Wildfire E" },
  { label: "HTC Wildfire E1", value: "HTC Wildfire E1" },
  { label: "HTC Wildfire X", value: "HTC Wildfire X" },
  { label: "HTC Desire 20 Pro", value: "HTC Desire 20 Pro" },
  { label: "HTC U20 5G", value: "HTC U20 5G" },
];

const motorolaPhoneList = [
  { label: "Motorola DROID", value: "Motorola DROID" },
  { label: "Motorola DROID X", value: "Motorola DROID X" },
  { label: "Motorola DROID 2", value: "Motorola DROID 2" },
  { label: "Motorola DROID 3", value: "Motorola DROID 3" },
  { label: "Motorola DROID 4", value: "Motorola DROID 4" },
  { label: "Motorola DROID Bionic", value: "Motorola DROID Bionic" },
  { label: "Motorola DROID RAZR", value: "Motorola DROID RAZR" },
  { label: "Motorola DROID RAZR Maxx", value: "Motorola DROID RAZR Maxx" },
  { label: "Motorola DROID Ultra", value: "Motorola DROID Ultra" },
  { label: "Motorola DROID Maxx", value: "Motorola DROID Maxx" },
  { label: "Motorola DROID Turbo", value: "Motorola DROID Turbo" },
  { label: "Motorola DROID Turbo 2", value: "Motorola DROID Turbo 2" },
  { label: "Motorola Moto X", value: "Motorola Moto X" },
  { label: "Motorola Moto X (2nd Gen)", value: "Motorola Moto X (2nd Gen)" },
  { label: "Motorola Moto X Play", value: "Motorola Moto X Play" },
  { label: "Motorola Moto X Force", value: "Motorola Moto X Force" },
  { label: "Motorola Moto G", value: "Motorola Moto G" },
  { label: "Motorola Moto G (2nd Gen)", value: "Motorola Moto G (2nd Gen)" },
  { label: "Motorola Moto G (3rd Gen)", value: "Motorola Moto G (3rd Gen)" },
  { label: "Motorola Moto G4", value: "Motorola Moto G4" },
  { label: "Motorola Moto G5", value: "Motorola Moto G5" },
  { label: "Motorola Moto G6", value: "Motorola Moto G6" },
  { label: "Motorola Moto G7", value: "Motorola Moto G7" },
  { label: "Motorola Moto G8", value: "Motorola Moto G8" },
  { label: "Motorola Moto G9", value: "Motorola Moto G9" },
  { label: "Motorola Moto G10", value: "Motorola Moto G10" },
  { label: "Motorola Moto G20", value: "Motorola Moto G20" },
  { label: "Motorola Moto G30", value: "Motorola Moto G30" },
  { label: "Motorola Moto G50", value: "Motorola Moto G50" },
  { label: "Motorola Moto G60", value: "Motorola Moto G60" },
  { label: "Motorola Moto G100", value: "Motorola Moto G100" },
  { label: "Motorola Moto E", value: "Motorola Moto E" },
  { label: "Motorola Moto E2", value: "Motorola Moto E2" },
  { label: "Motorola Moto E3", value: "Motorola Moto E3" },
  { label: "Motorola Moto E4", value: "Motorola Moto E4" },
  { label: "Motorola Moto E5", value: "Motorola Moto E5" },
  { label: "Motorola Moto E6", value: "Motorola Moto E6" },
  { label: "Motorola Moto E7", value: "Motorola Moto E7" },
  { label: "Motorola Moto E20", value: "Motorola Moto E20" },
  { label: "Motorola Moto Z", value: "Motorola Moto Z" },
  { label: "Motorola Moto Z2", value: "Motorola Moto Z2" },
  { label: "Motorola Moto Z3", value: "Motorola Moto Z3" },
  { label: "Motorola Moto Z4", value: "Motorola Moto Z4" },
  { label: "Motorola Edge", value: "Motorola Edge" },
  { label: "Motorola Edge+", value: "Motorola Edge+" },
  { label: "Motorola Edge 20", value: "Motorola Edge 20" },
  { label: "Motorola Edge 30", value: "Motorola Edge 30" },
  { label: "Motorola Edge 40", value: "Motorola Edge 40" },
  { label: "Motorola Edge 50", value: "Motorola Edge 50" },
  { label: "Motorola Razr 2019", value: "Motorola Razr 2019" },
  { label: "Motorola Razr 5G", value: "Motorola Razr 5G" },
  { label: "Motorola Razr 2022", value: "Motorola Razr 2022" },
  { label: "Motorola Razr 40", value: "Motorola Razr 40" },
  { label: "Motorola Razr 40 Ultra", value: "Motorola Razr 40 Ultra" },
];

const lenovoPhoneList = [
  { label: "Lenovo A1000", value: "Lenovo A1000" },
  { label: "Lenovo A2010", value: "Lenovo A2010" },
  { label: "Lenovo A6000", value: "Lenovo A6000" },
  { label: "Lenovo A7000", value: "Lenovo A7000" },
  { label: "Lenovo A850", value: "Lenovo A850" },
  { label: "Lenovo A880", value: "Lenovo A880" },
  { label: "Lenovo P70", value: "Lenovo P70" },
  { label: "Lenovo P780", value: "Lenovo P780" },
  { label: "Lenovo P90", value: "Lenovo P90" },
  { label: "Lenovo P1", value: "Lenovo P1" },
  { label: "Lenovo P2", value: "Lenovo P2" },
  { label: "Lenovo K3 Note", value: "Lenovo K3 Note" },
  { label: "Lenovo K4 Note", value: "Lenovo K4 Note" },
  { label: "Lenovo K5", value: "Lenovo K5" },
  { label: "Lenovo K5 Note", value: "Lenovo K5 Note" },
  { label: "Lenovo K6", value: "Lenovo K6" },
  { label: "Lenovo K6 Note", value: "Lenovo K6 Note" },
  { label: "Lenovo K8", value: "Lenovo K8" },
  { label: "Lenovo K8 Note", value: "Lenovo K8 Note" },
  { label: "Lenovo Z5", value: "Lenovo Z5" },
  { label: "Lenovo Z5 Pro", value: "Lenovo Z5 Pro" },
  { label: "Lenovo Z5 Pro GT", value: "Lenovo Z5 Pro GT" },
  { label: "Lenovo Z6", value: "Lenovo Z6" },
  { label: "Lenovo Z6 Pro", value: "Lenovo Z6 Pro" },
  { label: "Lenovo Z6 Youth", value: "Lenovo Z6 Youth" },
  { label: "Lenovo ZUK Z1", value: "Lenovo ZUK Z1" },
  { label: "Lenovo ZUK Z2", value: "Lenovo ZUK Z2" },
  { label: "Lenovo ZUK Z2 Pro", value: "Lenovo ZUK Z2 Pro" },
  { label: "Lenovo Legion Duel", value: "Lenovo Legion Duel" },
  { label: "Lenovo Legion Duel 2", value: "Lenovo Legion Duel 2" },
  { label: "Lenovo Legion Y90", value: "Lenovo Legion Y90" },
  { label: "Lenovo Phab 2", value: "Lenovo Phab 2" },
  { label: "Lenovo Phab 2 Pro", value: "Lenovo Phab 2 Pro" },
  { label: "Lenovo Phab 2 Plus", value: "Lenovo Phab 2 Plus" },
  { label: "Lenovo Vibe P1", value: "Lenovo Vibe P1" },
  { label: "Lenovo Vibe P1m", value: "Lenovo Vibe P1m" },
  { label: "Lenovo Vibe S1", value: "Lenovo Vibe S1" },
  { label: "Lenovo Vibe X2", value: "Lenovo Vibe X2" },
  { label: "Lenovo Vibe Z2", value: "Lenovo Vibe Z2" },
  { label: "Lenovo Vibe Z2 Pro", value: "Lenovo Vibe Z2 Pro" },
  { label: "Lenovo S60", value: "Lenovo S60" },
  { label: "Lenovo S90", value: "Lenovo S90" },
];

const xiaomiPhoneList = [
  // Mi Series (Flagships)
  { label: "Xiaomi Mi 1", value: "Xiaomi Mi 1" },
  { label: "Xiaomi Mi 2", value: "Xiaomi Mi 2" },
  { label: "Xiaomi Mi 3", value: "Xiaomi Mi 3" },
  { label: "Xiaomi Mi 4", value: "Xiaomi Mi 4" },
  { label: "Xiaomi Mi 5", value: "Xiaomi Mi 5" },
  { label: "Xiaomi Mi 6", value: "Xiaomi Mi 6" },
  { label: "Xiaomi Mi 8", value: "Xiaomi Mi 8" },
  { label: "Xiaomi Mi 9", value: "Xiaomi Mi 9" },
  { label: "Xiaomi Mi 10", value: "Xiaomi Mi 10" },
  { label: "Xiaomi Mi 11", value: "Xiaomi Mi 11" },

  // Xiaomi Number Series (Renamed from Mi Series)
  { label: "Xiaomi 12", value: "Xiaomi 12" },
  { label: "Xiaomi 12 Pro", value: "Xiaomi 12 Pro" },
  { label: "Xiaomi 12T", value: "Xiaomi 12T" },
  { label: "Xiaomi 13", value: "Xiaomi 13" },
  { label: "Xiaomi 13 Pro", value: "Xiaomi 13 Pro" },
  { label: "Xiaomi 13 Ultra", value: "Xiaomi 13 Ultra" },
  { label: "Xiaomi 14", value: "Xiaomi 14" },
  { label: "Xiaomi 14 Pro", value: "Xiaomi 14 Pro" },

  // Mi Mix Series (Innovative/Bezel-less)
  { label: "Xiaomi Mi Mix", value: "Xiaomi Mi Mix" },
  { label: "Xiaomi Mi Mix 2", value: "Xiaomi Mi Mix 2" },
  { label: "Xiaomi Mi Mix 3", value: "Xiaomi Mi Mix 3" },
  { label: "Xiaomi Mi Mix Alpha", value: "Xiaomi Mi Mix Alpha" },
  { label: "Xiaomi Mix 4", value: "Xiaomi Mix 4" },

  // Mi Note Series (Premium Mid-range)
  { label: "Xiaomi Mi Note", value: "Xiaomi Mi Note" },
  { label: "Xiaomi Mi Note 2", value: "Xiaomi Mi Note 2" },
  { label: "Xiaomi Mi Note 3", value: "Xiaomi Mi Note 3" },
  { label: "Xiaomi Mi Note 10", value: "Xiaomi Mi Note 10" },

  // Redmi Number Series (Budget)
  { label: "Redmi 1", value: "Redmi 1" },
  { label: "Redmi 2", value: "Redmi 2" },
  { label: "Redmi 3", value: "Redmi 3" },
  { label: "Redmi 4", value: "Redmi 4" },
  { label: "Redmi 5", value: "Redmi 5" },
  { label: "Redmi 6", value: "Redmi 6" },
  { label: "Redmi 7", value: "Redmi 7" },
  { label: "Redmi 8", value: "Redmi 8" },
  { label: "Redmi 9", value: "Redmi 9" },
  { label: "Redmi 10", value: "Redmi 10" },
  { label: "Redmi 11", value: "Redmi 11" },
  { label: "Redmi 12", value: "Redmi 12" },

  // Redmi Note Series (Mid-range)
  { label: "Redmi Note 3", value: "Redmi Note 3" },
  { label: "Redmi Note 4", value: "Redmi Note 4" },
  { label: "Redmi Note 5", value: "Redmi Note 5" },
  { label: "Redmi Note 6", value: "Redmi Note 6" },
  { label: "Redmi Note 7", value: "Redmi Note 7" },
  { label: "Redmi Note 8", value: "Redmi Note 8" },
  { label: "Redmi Note 9", value: "Redmi Note 9" },
  { label: "Redmi Note 10", value: "Redmi Note 10" },
  { label: "Redmi Note 11", value: "Redmi Note 11" },
  { label: "Redmi Note 12", value: "Redmi Note 12" },
  { label: "Redmi Note 13", value: "Redmi Note 13" },

  // Redmi K Series (Flagship Killer)
  { label: "Redmi K20", value: "Redmi K20" },
  { label: "Redmi K20 Pro", value: "Redmi K20 Pro" },
  { label: "Redmi K30", value: "Redmi K30" },
  { label: "Redmi K30 Pro", value: "Redmi K30 Pro" },
  { label: "Redmi K40", value: "Redmi K40" },
  { label: "Redmi K50", value: "Redmi K50" },
  { label: "Redmi K60", value: "Redmi K60" },

  // Poco Series (Performance-focused)
  { label: "Poco F1", value: "Poco F1" },
  { label: "Poco F2 Pro", value: "Poco F2 Pro" },
  { label: "Poco F3", value: "Poco F3" },
  { label: "Poco F4", value: "Poco F4" },
  { label: "Poco X2", value: "Poco X2" },
  { label: "Poco X3", value: "Poco X3" },
  { label: "Poco X4", value: "Poco X4" },
  { label: "Poco X5", value: "Poco X5" },
  { label: "Poco M2", value: "Poco M2" },
  { label: "Poco M3", value: "Poco M3" },
  { label: "Poco M4", value: "Poco M4" },
  { label: "Poco M5", value: "Poco M5" },

  // Black Shark Series (Gaming Phones)
  { label: "Black Shark", value: "Black Shark" },
  { label: "Black Shark 2", value: "Black Shark 2" },
  { label: "Black Shark 3", value: "Black Shark 3" },
  { label: "Black Shark 4", value: "Black Shark 4" },
  { label: "Black Shark 5", value: "Black Shark 5" },
];

const googlePhoneList = [
  // Google Nexus Series (Predecessor to Pixel)
  { label: "Google Nexus One", value: "Google Nexus One" },
  { label: "Google Nexus S", value: "Google Nexus S" },
  { label: "Google Galaxy Nexus", value: "Google Galaxy Nexus" },
  { label: "Google Nexus 4", value: "Google Nexus 4" },
  { label: "Google Nexus 5", value: "Google Nexus 5" },
  { label: "Google Nexus 6", value: "Google Nexus 6" },
  { label: "Google Nexus 5X", value: "Google Nexus 5X" },
  { label: "Google Nexus 6P", value: "Google Nexus 6P" },

  // Google Pixel Series (Flagship)
  { label: "Google Pixel", value: "Google Pixel" },
  { label: "Google Pixel XL", value: "Google Pixel XL" },
  { label: "Google Pixel 2", value: "Google Pixel 2" },
  { label: "Google Pixel 2 XL", value: "Google Pixel 2 XL" },
  { label: "Google Pixel 3", value: "Google Pixel 3" },
  { label: "Google Pixel 3 XL", value: "Google Pixel 3 XL" },
  { label: "Google Pixel 3a", value: "Google Pixel 3a" },
  { label: "Google Pixel 3a XL", value: "Google Pixel 3a XL" },
  { label: "Google Pixel 4", value: "Google Pixel 4" },
  { label: "Google Pixel 4 XL", value: "Google Pixel 4 XL" },
  { label: "Google Pixel 4a", value: "Google Pixel 4a" },
  { label: "Google Pixel 4a 5G", value: "Google Pixel 4a 5G" },
  { label: "Google Pixel 5", value: "Google Pixel 5" },
  { label: "Google Pixel 5a 5G", value: "Google Pixel 5a 5G" },
  { label: "Google Pixel 6", value: "Google Pixel 6" },
  { label: "Google Pixel 6 Pro", value: "Google Pixel 6 Pro" },
  { label: "Google Pixel 6a", value: "Google Pixel 6a" },
  { label: "Google Pixel 7", value: "Google Pixel 7" },
  { label: "Google Pixel 7 Pro", value: "Google Pixel 7 Pro" },
  { label: "Google Pixel 7a", value: "Google Pixel 7a" },
  { label: "Google Pixel 8", value: "Google Pixel 8" },
  { label: "Google Pixel 8 Pro", value: "Google Pixel 8 Pro" },

  // Google Pixel Fold Series (Foldable)
  { label: "Google Pixel Fold", value: "Google Pixel Fold" },

  // Google Pixel Tablet (Not a phone, but part of ecosystem)
  { label: "Google Pixel Tablet", value: "Google Pixel Tablet" },
];

const honorPhoneList = [
  // Honor Number Series (Main Flagship & Mid-range)
  { label: "Honor 3", value: "Honor 3" },
  { label: "Honor 4", value: "Honor 4" },
  { label: "Honor 5", value: "Honor 5" },
  { label: "Honor 6", value: "Honor 6" },
  { label: "Honor 7", value: "Honor 7" },
  { label: "Honor 8", value: "Honor 8" },
  { label: "Honor 9", value: "Honor 9" },
  { label: "Honor 10", value: "Honor 10" },
  { label: "Honor 20", value: "Honor 20" },
  { label: "Honor 30", value: "Honor 30" },
  { label: "Honor 50", value: "Honor 50" },
  { label: "Honor 60", value: "Honor 60" },
  { label: "Honor 70", value: "Honor 70" },
  { label: "Honor 80", value: "Honor 80" },
  { label: "Honor 90", value: "Honor 90" },

  // Honor X Series (Mid-range & Budget)
  { label: "Honor X6", value: "Honor X6" },
  { label: "Honor X7", value: "Honor X7" },
  { label: "Honor X8", value: "Honor X8" },
  { label: "Honor X9", value: "Honor X9" },
  { label: "Honor X10", value: "Honor X10" },
  { label: "Honor X20", value: "Honor X20" },
  { label: "Honor X30", value: "Honor X30" },

  // Honor Magic Series (Premium & Flagships)
  { label: "Honor Magic", value: "Honor Magic" },
  { label: "Honor Magic 2", value: "Honor Magic 2" },
  { label: "Honor Magic 3", value: "Honor Magic 3" },
  { label: "Honor Magic 4", value: "Honor Magic 4" },
  { label: "Honor Magic 5", value: "Honor Magic 5" },
  { label: "Honor Magic 6", value: "Honor Magic 6" },
  { label: "Honor Magic V", value: "Honor Magic V" }, // Foldable
  { label: "Honor Magic Vs", value: "Honor Magic Vs" }, // Foldable
  { label: "Honor Magic V2", value: "Honor Magic V2" }, // Foldable

  // Honor Play Series (Gaming & Performance)
  { label: "Honor Play", value: "Honor Play" },
  { label: "Honor Play 3", value: "Honor Play 3" },
  { label: "Honor Play 4", value: "Honor Play 4" },
  { label: "Honor Play 5", value: "Honor Play 5" },
  { label: "Honor Play 6", value: "Honor Play 6" },

  // Honor View (V) Series (Flagship Killers)
  { label: "Honor V8", value: "Honor V8" },
  { label: "Honor V9", value: "Honor V9" },
  { label: "Honor V10", value: "Honor V10" },
  { label: "Honor V20", value: "Honor V20" },
  { label: "Honor V30", value: "Honor V30" },

  // Honor Lite Series (Affordable Phones)
  { label: "Honor 7 Lite", value: "Honor 7 Lite" },
  { label: "Honor 8 Lite", value: "Honor 8 Lite" },
  { label: "Honor 9 Lite", value: "Honor 9 Lite" },
  { label: "Honor 10 Lite", value: "Honor 10 Lite" },
  { label: "Honor 20 Lite", value: "Honor 20 Lite" },
  { label: "Honor 30 Lite", value: "Honor 30 Lite" },
  { label: "Honor 50 Lite", value: "Honor 50 Lite" },
  { label: "Honor 60 Lite", value: "Honor 60 Lite" },
  { label: "Honor 70 Lite", value: "Honor 70 Lite" },

  // Honor Note Series (Large-Screen Phablets)
  { label: "Honor Note 8", value: "Honor Note 8" },
  { label: "Honor Note 10", value: "Honor Note 10" },
];

const oppoPhoneList = [
  // Oppo Find Series (Flagship)
  { label: "Oppo Find 5", value: "Oppo Find 5" },
  { label: "Oppo Find 7", value: "Oppo Find 7" },
  { label: "Oppo Find X", value: "Oppo Find X" },
  { label: "Oppo Find X2", value: "Oppo Find X2" },
  { label: "Oppo Find X3", value: "Oppo Find X3" },
  { label: "Oppo Find X3 Pro", value: "Oppo Find X3 Pro" },
  { label: "Oppo Find X5", value: "Oppo Find X5" },
  { label: "Oppo Find X5 Pro", value: "Oppo Find X5 Pro" },
  { label: "Oppo Find X6", value: "Oppo Find X6" },
  { label: "Oppo Find X6 Pro", value: "Oppo Find X6 Pro" },
  { label: "Oppo Find N", value: "Oppo Find N" }, // Foldable
  { label: "Oppo Find N2", value: "Oppo Find N2" }, // Foldable
  { label: "Oppo Find N3", value: "Oppo Find N3" }, // Foldable
  { label: "Oppo Find N3 Flip", value: "Oppo Find N3 Flip" }, // Flip Foldable

  // Oppo Reno Series (High-End & Mid-range)
  { label: "Oppo Reno", value: "Oppo Reno" },
  { label: "Oppo Reno 2", value: "Oppo Reno 2" },
  { label: "Oppo Reno 3", value: "Oppo Reno 3" },
  { label: "Oppo Reno 4", value: "Oppo Reno 4" },
  { label: "Oppo Reno 5", value: "Oppo Reno 5" },
  { label: "Oppo Reno 6", value: "Oppo Reno 6" },
  { label: "Oppo Reno 7", value: "Oppo Reno 7" },
  { label: "Oppo Reno 8", value: "Oppo Reno 8" },
  { label: "Oppo Reno 9", value: "Oppo Reno 9" },
  { label: "Oppo Reno 10", value: "Oppo Reno 10" },

  // Oppo F Series (Popular Mid-range)
  { label: "Oppo F1", value: "Oppo F1" },
  { label: "Oppo F1 Plus", value: "Oppo F1 Plus" },
  { label: "Oppo F3", value: "Oppo F3" },
  { label: "Oppo F5", value: "Oppo F5" },
  { label: "Oppo F7", value: "Oppo F7" },
  { label: "Oppo F9", value: "Oppo F9" },
  { label: "Oppo F11", value: "Oppo F11" },
  { label: "Oppo F15", value: "Oppo F15" },
  { label: "Oppo F17", value: "Oppo F17" },
  { label: "Oppo F19", value: "Oppo F19" },

  // Oppo A Series (Budget-Friendly)
  { label: "Oppo A1", value: "Oppo A1" },
  { label: "Oppo A3", value: "Oppo A3" },
  { label: "Oppo A5", value: "Oppo A5" },
  { label: "Oppo A7", value: "Oppo A7" },
  { label: "Oppo A9", value: "Oppo A9" },
  { label: "Oppo A11", value: "Oppo A11" },
  { label: "Oppo A12", value: "Oppo A12" },
  { label: "Oppo A15", value: "Oppo A15" },
  { label: "Oppo A16", value: "Oppo A16" },
  { label: "Oppo A17", value: "Oppo A17" },
  { label: "Oppo A31", value: "Oppo A31" },
  { label: "Oppo A53", value: "Oppo A53" },
  { label: "Oppo A55", value: "Oppo A55" },
  { label: "Oppo A57", value: "Oppo A57" },
  { label: "Oppo A74", value: "Oppo A74" },
  { label: "Oppo A95", value: "Oppo A95" },

  // Oppo K Series (Performance Mid-range)
  { label: "Oppo K1", value: "Oppo K1" },
  { label: "Oppo K3", value: "Oppo K3" },
  { label: "Oppo K5", value: "Oppo K5" },
  { label: "Oppo K7", value: "Oppo K7" },
  { label: "Oppo K9", value: "Oppo K9" },
  { label: "Oppo K10", value: "Oppo K10" },
  { label: "Oppo K11", value: "Oppo K11" },

  // Oppo R Series (Premium Mid-range, Discontinued)
  { label: "Oppo R1", value: "Oppo R1" },
  { label: "Oppo R5", value: "Oppo R5" },
  { label: "Oppo R7", value: "Oppo R7" },
  { label: "Oppo R9", value: "Oppo R9" },
  { label: "Oppo R11", value: "Oppo R11" },
  { label: "Oppo R15", value: "Oppo R15" },
  { label: "Oppo R17", value: "Oppo R17" },
  { label: "Oppo R19", value: "Oppo R19" },
];

const realmePhoneList = [
  // Realme Number Series (Main Flagship & Mid-range)
  { label: "Realme 1", value: "Realme 1" },
  { label: "Realme 2", value: "Realme 2" },
  { label: "Realme 3", value: "Realme 3" },
  { label: "Realme 3 Pro", value: "Realme 3 Pro" },
  { label: "Realme 5", value: "Realme 5" },
  { label: "Realme 5 Pro", value: "Realme 5 Pro" },
  { label: "Realme 6", value: "Realme 6" },
  { label: "Realme 6 Pro", value: "Realme 6 Pro" },
  { label: "Realme 7", value: "Realme 7" },
  { label: "Realme 7 Pro", value: "Realme 7 Pro" },
  { label: "Realme 8", value: "Realme 8" },
  { label: "Realme 8 Pro", value: "Realme 8 Pro" },
  { label: "Realme 9", value: "Realme 9" },
  { label: "Realme 9 Pro", value: "Realme 9 Pro" },
  { label: "Realme 10", value: "Realme 10" },
  { label: "Realme 10 Pro", value: "Realme 10 Pro" },
  { label: "Realme 11", value: "Realme 11" },
  { label: "Realme 11 Pro", value: "Realme 11 Pro" },

  // Realme GT Series (Flagship & Gaming)
  { label: "Realme GT", value: "Realme GT" },
  { label: "Realme GT Neo", value: "Realme GT Neo" },
  { label: "Realme GT Neo 2", value: "Realme GT Neo 2" },
  { label: "Realme GT Neo 3", value: "Realme GT Neo 3" },
  { label: "Realme GT Neo 5", value: "Realme GT Neo 5" },
  { label: "Realme GT2", value: "Realme GT2" },
  { label: "Realme GT2 Pro", value: "Realme GT2 Pro" },

  // Realme X Series (Mid-range & Flagship Killers)
  { label: "Realme X", value: "Realme X" },
  { label: "Realme X2", value: "Realme X2" },
  { label: "Realme X2 Pro", value: "Realme X2 Pro" },
  { label: "Realme X3", value: "Realme X3" },
  { label: "Realme X3 SuperZoom", value: "Realme X3 SuperZoom" },
  { label: "Realme X50", value: "Realme X50" },
  { label: "Realme X50 Pro", value: "Realme X50 Pro" },

  // Realme C Series (Budget Smartphones)
  { label: "Realme C1", value: "Realme C1" },
  { label: "Realme C2", value: "Realme C2" },
  { label: "Realme C3", value: "Realme C3" },
  { label: "Realme C11", value: "Realme C11" },
  { label: "Realme C12", value: "Realme C12" },
  { label: "Realme C15", value: "Realme C15" },
  { label: "Realme C17", value: "Realme C17" },
  { label: "Realme C21", value: "Realme C21" },
  { label: "Realme C25", value: "Realme C25" },
  { label: "Realme C30", value: "Realme C30" },
  { label: "Realme C31", value: "Realme C31" },
  { label: "Realme C33", value: "Realme C33" },
  { label: "Realme C35", value: "Realme C35" },

  // Realme Narzo Series (Gaming & Performance)
  { label: "Realme Narzo 10", value: "Realme Narzo 10" },
  { label: "Realme Narzo 20", value: "Realme Narzo 20" },
  { label: "Realme Narzo 30", value: "Realme Narzo 30" },
  { label: "Realme Narzo 50", value: "Realme Narzo 50" },

  // Realme V Series (China-exclusive, Mid-range)
  { label: "Realme V3", value: "Realme V3" },
  { label: "Realme V5", value: "Realme V5" },
  { label: "Realme V11", value: "Realme V11" },
  { label: "Realme V13", value: "Realme V13" },
  { label: "Realme V15", value: "Realme V15" },
  { label: "Realme V20", value: "Realme V20" },
  { label: "Realme V23", value: "Realme V23" },

  // Realme Pad (Tablets, not phones but part of ecosystem)
  { label: "Realme Pad", value: "Realme Pad" },
  { label: "Realme Pad Mini", value: "Realme Pad Mini" },
  { label: "Realme Pad X", value: "Realme Pad X" },
];

const oneplusPhoneList = [
  // OnePlus Number Series (Flagship)
  { label: "OnePlus One", value: "OnePlus One" },
  { label: "OnePlus 2", value: "OnePlus 2" },
  { label: "OnePlus 3", value: "OnePlus 3" },
  { label: "OnePlus 3T", value: "OnePlus 3T" },
  { label: "OnePlus 5", value: "OnePlus 5" },
  { label: "OnePlus 5T", value: "OnePlus 5T" },
  { label: "OnePlus 6", value: "OnePlus 6" },
  { label: "OnePlus 6T", value: "OnePlus 6T" },
  { label: "OnePlus 7", value: "OnePlus 7" },
  { label: "OnePlus 7 Pro", value: "OnePlus 7 Pro" },
  { label: "OnePlus 7T", value: "OnePlus 7T" },
  { label: "OnePlus 7T Pro", value: "OnePlus 7T Pro" },
  { label: "OnePlus 8", value: "OnePlus 8" },
  { label: "OnePlus 8 Pro", value: "OnePlus 8 Pro" },
  { label: "OnePlus 8T", value: "OnePlus 8T" },
  { label: "OnePlus 9", value: "OnePlus 9" },
  { label: "OnePlus 9 Pro", value: "OnePlus 9 Pro" },
  { label: "OnePlus 9R", value: "OnePlus 9R" },
  { label: "OnePlus 10 Pro", value: "OnePlus 10 Pro" },
  { label: "OnePlus 10R", value: "OnePlus 10R" },
  { label: "OnePlus 11", value: "OnePlus 11" },
  { label: "OnePlus 11R", value: "OnePlus 11R" },
  { label: "OnePlus 12", value: "OnePlus 12" },
  { label: "OnePlus 12R", value: "OnePlus 12R" },

  // OnePlus Nord Series (Mid-range & Affordable Flagship)
  { label: "OnePlus Nord", value: "OnePlus Nord" },
  { label: "OnePlus Nord 2", value: "OnePlus Nord 2" },
  { label: "OnePlus Nord 2T", value: "OnePlus Nord 2T" },
  { label: "OnePlus Nord 3", value: "OnePlus Nord 3" },
  { label: "OnePlus Nord CE", value: "OnePlus Nord CE" },
  { label: "OnePlus Nord CE 2", value: "OnePlus Nord CE 2" },
  { label: "OnePlus Nord CE 2 Lite", value: "OnePlus Nord CE 2 Lite" },
  { label: "OnePlus Nord CE 3", value: "OnePlus Nord CE 3" },
  { label: "OnePlus Nord CE 3 Lite", value: "OnePlus Nord CE 3 Lite" },
  { label: "OnePlus Nord N100", value: "OnePlus Nord N100" },
  { label: "OnePlus Nord N10 5G", value: "OnePlus Nord N10 5G" },
  { label: "OnePlus Nord N20", value: "OnePlus Nord N20" },
  { label: "OnePlus Nord N30", value: "OnePlus Nord N30" },

  // OnePlus Ace Series (Performance & Gaming)
  { label: "OnePlus Ace", value: "OnePlus Ace" },
  { label: "OnePlus Ace 2", value: "OnePlus Ace 2" },
  { label: "OnePlus Ace 2 Pro", value: "OnePlus Ace 2 Pro" },
  { label: "OnePlus Ace Racing Edition", value: "OnePlus Ace Racing Edition" },

  // OnePlus Open Series (Foldable)
  { label: "OnePlus Open", value: "OnePlus Open" },
];

const nothingPhoneList = [
  { label: "Nothing Phone (1)", value: "Nothing Phone (1)" },
  { label: "Nothing Phone (2)", value: "Nothing Phone (2)" },
  { label: "Nothing Phone (2a)", value: "Nothing Phone (2a)" },
];

const vivoPhoneList = [
  // Vivo X Series (Flagship & High-End)
  { label: "Vivo X1", value: "Vivo X1" },
  { label: "Vivo X3", value: "Vivo X3" },
  { label: "Vivo X5", value: "Vivo X5" },
  { label: "Vivo X7", value: "Vivo X7" },
  { label: "Vivo X9", value: "Vivo X9" },
  { label: "Vivo X20", value: "Vivo X20" },
  { label: "Vivo X21", value: "Vivo X21" },
  { label: "Vivo X23", value: "Vivo X23" },
  { label: "Vivo X27", value: "Vivo X27" },
  { label: "Vivo X50", value: "Vivo X50" },
  { label: "Vivo X60", value: "Vivo X60" },
  { label: "Vivo X70", value: "Vivo X70" },
  { label: "Vivo X80", value: "Vivo X80" },
  { label: "Vivo X90", value: "Vivo X90" },
  { label: "Vivo X100", value: "Vivo X100" },

  // Vivo Y Series (Budget & Mid-range)
  { label: "Vivo Y1s", value: "Vivo Y1s" },
  { label: "Vivo Y3", value: "Vivo Y3" },
  { label: "Vivo Y5", value: "Vivo Y5" },
  { label: "Vivo Y7", value: "Vivo Y7" },
  { label: "Vivo Y11", value: "Vivo Y11" },
  { label: "Vivo Y12", value: "Vivo Y12" },
  { label: "Vivo Y15", value: "Vivo Y15" },
  { label: "Vivo Y17", value: "Vivo Y17" },
  { label: "Vivo Y19", value: "Vivo Y19" },
  { label: "Vivo Y20", value: "Vivo Y20" },
  { label: "Vivo Y21", value: "Vivo Y21" },
  { label: "Vivo Y30", value: "Vivo Y30" },
  { label: "Vivo Y31", value: "Vivo Y31" },
  { label: "Vivo Y33", value: "Vivo Y33" },
  { label: "Vivo Y50", value: "Vivo Y50" },
  { label: "Vivo Y51", value: "Vivo Y51" },
  { label: "Vivo Y53", value: "Vivo Y53" },
  { label: "Vivo Y55", value: "Vivo Y55" },
  { label: "Vivo Y70", value: "Vivo Y70" },
  { label: "Vivo Y72", value: "Vivo Y72" },

  // Vivo V Series (Premium Mid-range & Camera-focused)
  { label: "Vivo V1", value: "Vivo V1" },
  { label: "Vivo V3", value: "Vivo V3" },
  { label: "Vivo V5", value: "Vivo V5" },
  { label: "Vivo V7", value: "Vivo V7" },
  { label: "Vivo V9", value: "Vivo V9" },
  { label: "Vivo V11", value: "Vivo V11" },
  { label: "Vivo V15", value: "Vivo V15" },
  { label: "Vivo V17", value: "Vivo V17" },
  { label: "Vivo V19", value: "Vivo V19" },
  { label: "Vivo V20", value: "Vivo V20" },
  { label: "Vivo V21", value: "Vivo V21" },
  { label: "Vivo V23", value: "Vivo V23" },
  { label: "Vivo V25", value: "Vivo V25" },
  { label: "Vivo V27", value: "Vivo V27" },
  { label: "Vivo V29", value: "Vivo V29" },

  // Vivo iQOO Series (Gaming & High Performance)
  { label: "iQOO 3", value: "iQOO 3" },
  { label: "iQOO 5", value: "iQOO 5" },
  { label: "iQOO 7", value: "iQOO 7" },
  { label: "iQOO 8", value: "iQOO 8" },
  { label: "iQOO 9", value: "iQOO 9" },
  { label: "iQOO 10", value: "iQOO 10" },
  { label: "iQOO 11", value: "iQOO 11" },
  { label: "iQOO 12", value: "iQOO 12" },
  { label: "iQOO Neo 3", value: "iQOO Neo 3" },
  { label: "iQOO Neo 5", value: "iQOO Neo 5" },
  { label: "iQOO Neo 6", value: "iQOO Neo 6" },
  { label: "iQOO Neo 7", value: "iQOO Neo 7" },
  { label: "iQOO Z1", value: "iQOO Z1" },
  { label: "iQOO Z3", value: "iQOO Z3" },
  { label: "iQOO Z5", value: "iQOO Z5" },
  { label: "iQOO Z7", value: "iQOO Z7" },

  // Vivo Nex Series (Experimental Flagships)
  { label: "Vivo Nex", value: "Vivo Nex" },
  { label: "Vivo Nex 2", value: "Vivo Nex 2" },
  { label: "Vivo Nex 3", value: "Vivo Nex 3" },

  // Vivo T Series (Performance Mid-range)
  { label: "Vivo T1", value: "Vivo T1" },
  { label: "Vivo T2", value: "Vivo T2" },
  { label: "Vivo T3", value: "Vivo T3" },
];

export const smartphoneList = [
  {
    label: "Apple",
    options: applePhoneList,
  },
  {
    label: "Samsung",
    options: samsungPhoneList,
  },
  {
    label: "Huawei",
    options: huaweiPhoneList,
  },
  {
    label: "Nokia",
    options: nokiaPhoneList,
  },
  {
    label: "Sony",
    options: sonyPhoneList,
  },
  {
    label: "LG",
    options: lgPhoneList,
  },
  {
    label: "HTC",
    options: htcPhoneList,
  },
  {
    label: "Motorola",
    options: motorolaPhoneList,
  },
  {
    label: "Lenovo",
    options: lenovoPhoneList,
  },
  {
    label: "Xiaomi",
    options: xiaomiPhoneList,
  },
  {
    label: "Google",
    options: googlePhoneList,
  },
  {
    label: "Honor",
    options: honorPhoneList,
  },
  {
    label: "Oppo",
    options: oppoPhoneList,
  },
  {
    label: "Realme",
    options: realmePhoneList,
  },
  {
    label: "Oneplus",
    options: oneplusPhoneList,
  },
  {
    label: "Nothing",
    options: nothingPhoneList,
  },
  {
    label: "Vivo",
    options: vivoPhoneList,
  },
];
